#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm.git'
cookbook 'build-essential'
cookbook 'ack'
cookbook 'python'
cookbook 'tmux'
cookbook 'vim'
cookbook 'zsh'
cookbook 'git'
