#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rvm'
cookbook 'build-essential'
cookbook 'ack'
cookbook 'python'
cookbook 'ruby'
cookbook 'tmux'
cookbook 'vim'
cookbook 'git'
