#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'rvm', 
  :github => 'fnichol/chef-rvm'
cookbook 'build-essential', 
  :github => 'opscode-cookbooks/build-essential'
cookbook 'ack', 
  :github => 'opscode-cookbooks/ack'
cookbook 'tmux'
cookbook 'vim'
cookbook 'apt'
cookbook 'git'
